# Generated by Django 4.1.1 on 2022-10-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platerak', '0002_platerak_izena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platerak',
            name='prezioa',
            field=models.CharField(max_length=100),
        ),
    ]
