# Generated by Django 4.1.1 on 2022-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=9)),
                ('kontaktuko_telefono_zenbakia', models.CharField(max_length=9)),
                ('saldo', models.TextField()),
            ],
        ),
    ]
